<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bloock_keys_entities.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.AccessControlSecret</code>
 */
class AccessControlSecret extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string secret = 1;</code>
     */
    protected $secret = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $secret
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BloockKeysEntities::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string secret = 1;</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * Generated from protobuf field <code>string secret = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret = $var;

        return $this;
    }

}

