<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record_entities.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.AuthenticityDetails</code>
 */
class AuthenticityDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .bloock.Signature signatures = 1;</code>
     */
    private $signatures;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bloock\Signature[]|\Google\Protobuf\Internal\RepeatedField $signatures
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RecordEntities::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.Signature signatures = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignatures()
    {
        return $this->signatures;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.Signature signatures = 1;</code>
     * @param \Bloock\Signature[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\Signature::class);
        $this->signatures = $arr;

        return $this;
    }

}

