<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity_v2.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.BuildSchemaRequestV2</code>
 */
class BuildSchemaRequestV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     */
    protected $config_data = null;
    /**
     * Generated from protobuf field <code>string display_name = 2;</code>
     */
    protected $display_name = '';
    /**
     * Generated from protobuf field <code>string schema_type = 3;</code>
     */
    protected $schema_type = '';
    /**
     * Generated from protobuf field <code>string version = 4;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>string description = 5;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>repeated .bloock.StringAttributeDefinitionV2 string_attributes = 6;</code>
     */
    private $string_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.IntegerAttributeDefinitionV2 integer_attributes = 7;</code>
     */
    private $integer_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.DecimalAttributeDefinitionV2 decimal_attributes = 8;</code>
     */
    private $decimal_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.BooleanAttributeDefinitionV2 boolean_attributes = 9;</code>
     */
    private $boolean_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.DateAttributeDefinitionV2 date_attributes = 10;</code>
     */
    private $date_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.DateTimeAttributeDefinitionV2 datetime_attributes = 11;</code>
     */
    private $datetime_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.StringEnumAttributeDefinitionV2 string_enum_attributes = 12;</code>
     */
    private $string_enum_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.IntegerEnumAttributeDefinitionV2 integer_enum_attributes = 13;</code>
     */
    private $integer_enum_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.DecimalEnumAttributeDefinitionV2 decimal_enum_attributes = 14;</code>
     */
    private $decimal_enum_attributes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bloock\ConfigData $config_data
     *     @type string $display_name
     *     @type string $schema_type
     *     @type string $version
     *     @type string $description
     *     @type \Bloock\StringAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $string_attributes
     *     @type \Bloock\IntegerAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $integer_attributes
     *     @type \Bloock\DecimalAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $decimal_attributes
     *     @type \Bloock\BooleanAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $boolean_attributes
     *     @type \Bloock\DateAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $date_attributes
     *     @type \Bloock\DateTimeAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $datetime_attributes
     *     @type \Bloock\StringEnumAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $string_enum_attributes
     *     @type \Bloock\IntegerEnumAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $integer_enum_attributes
     *     @type \Bloock\DecimalEnumAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $decimal_enum_attributes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\IdentityV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @return \Bloock\ConfigData|null
     */
    public function getConfigData()
    {
        return $this->config_data;
    }

    public function hasConfigData()
    {
        return isset($this->config_data);
    }

    public function clearConfigData()
    {
        unset($this->config_data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @param \Bloock\ConfigData $var
     * @return $this
     */
    public function setConfigData($var)
    {
        GPBUtil::checkMessage($var, \Bloock\ConfigData::class);
        $this->config_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema_type = 3;</code>
     * @return string
     */
    public function getSchemaType()
    {
        return $this->schema_type;
    }

    /**
     * Generated from protobuf field <code>string schema_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaType($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 4;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.StringAttributeDefinitionV2 string_attributes = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStringAttributes()
    {
        return $this->string_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.StringAttributeDefinitionV2 string_attributes = 6;</code>
     * @param \Bloock\StringAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStringAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\StringAttributeDefinitionV2::class);
        $this->string_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.IntegerAttributeDefinitionV2 integer_attributes = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIntegerAttributes()
    {
        return $this->integer_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.IntegerAttributeDefinitionV2 integer_attributes = 7;</code>
     * @param \Bloock\IntegerAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIntegerAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\IntegerAttributeDefinitionV2::class);
        $this->integer_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DecimalAttributeDefinitionV2 decimal_attributes = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDecimalAttributes()
    {
        return $this->decimal_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DecimalAttributeDefinitionV2 decimal_attributes = 8;</code>
     * @param \Bloock\DecimalAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDecimalAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\DecimalAttributeDefinitionV2::class);
        $this->decimal_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.BooleanAttributeDefinitionV2 boolean_attributes = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBooleanAttributes()
    {
        return $this->boolean_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.BooleanAttributeDefinitionV2 boolean_attributes = 9;</code>
     * @param \Bloock\BooleanAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBooleanAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\BooleanAttributeDefinitionV2::class);
        $this->boolean_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateAttributeDefinitionV2 date_attributes = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDateAttributes()
    {
        return $this->date_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateAttributeDefinitionV2 date_attributes = 10;</code>
     * @param \Bloock\DateAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDateAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\DateAttributeDefinitionV2::class);
        $this->date_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateTimeAttributeDefinitionV2 datetime_attributes = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDatetimeAttributes()
    {
        return $this->datetime_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateTimeAttributeDefinitionV2 datetime_attributes = 11;</code>
     * @param \Bloock\DateTimeAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDatetimeAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\DateTimeAttributeDefinitionV2::class);
        $this->datetime_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.StringEnumAttributeDefinitionV2 string_enum_attributes = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStringEnumAttributes()
    {
        return $this->string_enum_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.StringEnumAttributeDefinitionV2 string_enum_attributes = 12;</code>
     * @param \Bloock\StringEnumAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStringEnumAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\StringEnumAttributeDefinitionV2::class);
        $this->string_enum_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.IntegerEnumAttributeDefinitionV2 integer_enum_attributes = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIntegerEnumAttributes()
    {
        return $this->integer_enum_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.IntegerEnumAttributeDefinitionV2 integer_enum_attributes = 13;</code>
     * @param \Bloock\IntegerEnumAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIntegerEnumAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\IntegerEnumAttributeDefinitionV2::class);
        $this->integer_enum_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DecimalEnumAttributeDefinitionV2 decimal_enum_attributes = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDecimalEnumAttributes()
    {
        return $this->decimal_enum_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DecimalEnumAttributeDefinitionV2 decimal_enum_attributes = 14;</code>
     * @param \Bloock\DecimalEnumAttributeDefinitionV2[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDecimalEnumAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\DecimalEnumAttributeDefinitionV2::class);
        $this->decimal_enum_attributes = $arr;

        return $this;
    }

}

