<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.CreateCredentialRequest</code>
 */
class CreateCredentialRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     */
    protected $config_data = null;
    /**
     * Generated from protobuf field <code>string schema_id = 2;</code>
     */
    protected $schema_id = '';
    /**
     * Generated from protobuf field <code>string holder_key = 3;</code>
     */
    protected $holder_key = '';
    /**
     * Generated from protobuf field <code>repeated .bloock.BooleanAttribute boolean_attributes = 4;</code>
     */
    private $boolean_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.DateAttribute date_attributes = 5;</code>
     */
    private $date_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.DateTimeAttribute datetime_attributes = 6;</code>
     */
    private $datetime_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.MultiChoiceAttribute multichoice_attributes = 7;</code>
     */
    private $multichoice_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.NumberAttribute number_attributes = 8;</code>
     */
    private $number_attributes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bloock\ConfigData $config_data
     *     @type string $schema_id
     *     @type string $holder_key
     *     @type array<\Bloock\BooleanAttribute>|\Google\Protobuf\Internal\RepeatedField $boolean_attributes
     *     @type array<\Bloock\DateAttribute>|\Google\Protobuf\Internal\RepeatedField $date_attributes
     *     @type array<\Bloock\DateTimeAttribute>|\Google\Protobuf\Internal\RepeatedField $datetime_attributes
     *     @type array<\Bloock\MultiChoiceAttribute>|\Google\Protobuf\Internal\RepeatedField $multichoice_attributes
     *     @type array<\Bloock\NumberAttribute>|\Google\Protobuf\Internal\RepeatedField $number_attributes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @return \Bloock\ConfigData|null
     */
    public function getConfigData()
    {
        return $this->config_data;
    }

    public function hasConfigData()
    {
        return isset($this->config_data);
    }

    public function clearConfigData()
    {
        unset($this->config_data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @param \Bloock\ConfigData $var
     * @return $this
     */
    public function setConfigData($var)
    {
        GPBUtil::checkMessage($var, \Bloock\ConfigData::class);
        $this->config_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema_id = 2;</code>
     * @return string
     */
    public function getSchemaId()
    {
        return $this->schema_id;
    }

    /**
     * Generated from protobuf field <code>string schema_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaId($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string holder_key = 3;</code>
     * @return string
     */
    public function getHolderKey()
    {
        return $this->holder_key;
    }

    /**
     * Generated from protobuf field <code>string holder_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHolderKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->holder_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.BooleanAttribute boolean_attributes = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBooleanAttributes()
    {
        return $this->boolean_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.BooleanAttribute boolean_attributes = 4;</code>
     * @param array<\Bloock\BooleanAttribute>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBooleanAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\BooleanAttribute::class);
        $this->boolean_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateAttribute date_attributes = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDateAttributes()
    {
        return $this->date_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateAttribute date_attributes = 5;</code>
     * @param array<\Bloock\DateAttribute>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDateAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\DateAttribute::class);
        $this->date_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateTimeAttribute datetime_attributes = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDatetimeAttributes()
    {
        return $this->datetime_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateTimeAttribute datetime_attributes = 6;</code>
     * @param array<\Bloock\DateTimeAttribute>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDatetimeAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\DateTimeAttribute::class);
        $this->datetime_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.MultiChoiceAttribute multichoice_attributes = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMultichoiceAttributes()
    {
        return $this->multichoice_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.MultiChoiceAttribute multichoice_attributes = 7;</code>
     * @param array<\Bloock\MultiChoiceAttribute>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMultichoiceAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\MultiChoiceAttribute::class);
        $this->multichoice_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.NumberAttribute number_attributes = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNumberAttributes()
    {
        return $this->number_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.NumberAttribute number_attributes = 8;</code>
     * @param array<\Bloock\NumberAttribute>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNumberAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\NumberAttribute::class);
        $this->number_attributes = $arr;

        return $this;
    }

}

