<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.CreateCredentialRequest</code>
 */
class CreateCredentialRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     */
    protected $config_data = null;
    /**
     * Generated from protobuf field <code>string schema_id = 2;</code>
     */
    protected $schema_id = '';
    /**
     * Generated from protobuf field <code>string holder_did = 3;</code>
     */
    protected $holder_did = '';
    /**
     * Generated from protobuf field <code>int64 expiration = 4;</code>
     */
    protected $expiration = 0;
    /**
     * Generated from protobuf field <code>optional int32 version = 5;</code>
     */
    protected $version = null;
    /**
     * Generated from protobuf field <code>.bloock.Key key = 6;</code>
     */
    protected $key = null;
    /**
     * Generated from protobuf field <code>repeated .bloock.StringAttribute string_attributes = 7;</code>
     */
    private $string_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.IntegerAttribute integer_attributes = 8;</code>
     */
    private $integer_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.DecimalAttribute decimal_attributes = 9;</code>
     */
    private $decimal_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.BooleanAttribute boolean_attributes = 10;</code>
     */
    private $boolean_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.DateAttribute date_attributes = 11;</code>
     */
    private $date_attributes;
    /**
     * Generated from protobuf field <code>repeated .bloock.DateTimeAttribute datetime_attributes = 12;</code>
     */
    private $datetime_attributes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bloock\ConfigData $config_data
     *     @type string $schema_id
     *     @type string $holder_did
     *     @type int|string $expiration
     *     @type int $version
     *     @type \Bloock\Key $key
     *     @type \Bloock\StringAttribute[]|\Google\Protobuf\Internal\RepeatedField $string_attributes
     *     @type \Bloock\IntegerAttribute[]|\Google\Protobuf\Internal\RepeatedField $integer_attributes
     *     @type \Bloock\DecimalAttribute[]|\Google\Protobuf\Internal\RepeatedField $decimal_attributes
     *     @type \Bloock\BooleanAttribute[]|\Google\Protobuf\Internal\RepeatedField $boolean_attributes
     *     @type \Bloock\DateAttribute[]|\Google\Protobuf\Internal\RepeatedField $date_attributes
     *     @type \Bloock\DateTimeAttribute[]|\Google\Protobuf\Internal\RepeatedField $datetime_attributes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @return \Bloock\ConfigData|null
     */
    public function getConfigData()
    {
        return $this->config_data;
    }

    public function hasConfigData()
    {
        return isset($this->config_data);
    }

    public function clearConfigData()
    {
        unset($this->config_data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @param \Bloock\ConfigData $var
     * @return $this
     */
    public function setConfigData($var)
    {
        GPBUtil::checkMessage($var, \Bloock\ConfigData::class);
        $this->config_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema_id = 2;</code>
     * @return string
     */
    public function getSchemaId()
    {
        return $this->schema_id;
    }

    /**
     * Generated from protobuf field <code>string schema_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaId($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string holder_did = 3;</code>
     * @return string
     */
    public function getHolderDid()
    {
        return $this->holder_did;
    }

    /**
     * Generated from protobuf field <code>string holder_did = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHolderDid($var)
    {
        GPBUtil::checkString($var, True);
        $this->holder_did = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expiration = 4;</code>
     * @return int|string
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>int64 expiration = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkInt64($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 version = 5;</code>
     * @return int
     */
    public function getVersion()
    {
        return isset($this->version) ? $this->version : 0;
    }

    public function hasVersion()
    {
        return isset($this->version);
    }

    public function clearVersion()
    {
        unset($this->version);
    }

    /**
     * Generated from protobuf field <code>optional int32 version = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bloock.Key key = 6;</code>
     * @return \Bloock\Key|null
     */
    public function getKey()
    {
        return $this->key;
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * Generated from protobuf field <code>.bloock.Key key = 6;</code>
     * @param \Bloock\Key $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkMessage($var, \Bloock\Key::class);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.StringAttribute string_attributes = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStringAttributes()
    {
        return $this->string_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.StringAttribute string_attributes = 7;</code>
     * @param \Bloock\StringAttribute[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStringAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\StringAttribute::class);
        $this->string_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.IntegerAttribute integer_attributes = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIntegerAttributes()
    {
        return $this->integer_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.IntegerAttribute integer_attributes = 8;</code>
     * @param \Bloock\IntegerAttribute[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIntegerAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\IntegerAttribute::class);
        $this->integer_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DecimalAttribute decimal_attributes = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDecimalAttributes()
    {
        return $this->decimal_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DecimalAttribute decimal_attributes = 9;</code>
     * @param \Bloock\DecimalAttribute[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDecimalAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\DecimalAttribute::class);
        $this->decimal_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.BooleanAttribute boolean_attributes = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBooleanAttributes()
    {
        return $this->boolean_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.BooleanAttribute boolean_attributes = 10;</code>
     * @param \Bloock\BooleanAttribute[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBooleanAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\BooleanAttribute::class);
        $this->boolean_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateAttribute date_attributes = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDateAttributes()
    {
        return $this->date_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateAttribute date_attributes = 11;</code>
     * @param \Bloock\DateAttribute[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDateAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\DateAttribute::class);
        $this->date_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateTimeAttribute datetime_attributes = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDatetimeAttributes()
    {
        return $this->datetime_attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.DateTimeAttribute datetime_attributes = 12;</code>
     * @param \Bloock\DateTimeAttribute[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDatetimeAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\DateTimeAttribute::class);
        $this->datetime_attributes = $arr;

        return $this;
    }

}

