<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.CredentialOfferFromJsonResponse</code>
 */
class CredentialOfferFromJsonResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bloock.CredentialOffer credential_offer = 1;</code>
     */
    protected $credential_offer = null;
    /**
     * Generated from protobuf field <code>optional .bloock.Error error = 2;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bloock\CredentialOffer $credential_offer
     *     @type \Bloock\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bloock.CredentialOffer credential_offer = 1;</code>
     * @return \Bloock\CredentialOffer|null
     */
    public function getCredentialOffer()
    {
        return $this->credential_offer;
    }

    public function hasCredentialOffer()
    {
        return isset($this->credential_offer);
    }

    public function clearCredentialOffer()
    {
        unset($this->credential_offer);
    }

    /**
     * Generated from protobuf field <code>.bloock.CredentialOffer credential_offer = 1;</code>
     * @param \Bloock\CredentialOffer $var
     * @return $this
     */
    public function setCredentialOffer($var)
    {
        GPBUtil::checkMessage($var, \Bloock\CredentialOffer::class);
        $this->credential_offer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .bloock.Error error = 2;</code>
     * @return \Bloock\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>optional .bloock.Error error = 2;</code>
     * @param \Bloock\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Bloock\Error::class);
        $this->error = $var;

        return $this;
    }

}

