<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryption.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.EncryptRequest</code>
 */
class EncryptRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     */
    protected $config_data = null;
    /**
     * Generated from protobuf field <code>.bloock.Record record = 2;</code>
     */
    protected $record = null;
    /**
     * Generated from protobuf field <code>.bloock.Encrypter encrypter = 3;</code>
     */
    protected $encrypter = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bloock\ConfigData $config_data
     *     @type \Bloock\Record $record
     *     @type \Bloock\Encrypter $encrypter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Encryption::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @return \Bloock\ConfigData|null
     */
    public function getConfigData()
    {
        return $this->config_data;
    }

    public function hasConfigData()
    {
        return isset($this->config_data);
    }

    public function clearConfigData()
    {
        unset($this->config_data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @param \Bloock\ConfigData $var
     * @return $this
     */
    public function setConfigData($var)
    {
        GPBUtil::checkMessage($var, \Bloock\ConfigData::class);
        $this->config_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bloock.Record record = 2;</code>
     * @return \Bloock\Record|null
     */
    public function getRecord()
    {
        return $this->record;
    }

    public function hasRecord()
    {
        return isset($this->record);
    }

    public function clearRecord()
    {
        unset($this->record);
    }

    /**
     * Generated from protobuf field <code>.bloock.Record record = 2;</code>
     * @param \Bloock\Record $var
     * @return $this
     */
    public function setRecord($var)
    {
        GPBUtil::checkMessage($var, \Bloock\Record::class);
        $this->record = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bloock.Encrypter encrypter = 3;</code>
     * @return \Bloock\Encrypter|null
     */
    public function getEncrypter()
    {
        return $this->encrypter;
    }

    public function hasEncrypter()
    {
        return isset($this->encrypter);
    }

    public function clearEncrypter()
    {
        unset($this->encrypter);
    }

    /**
     * Generated from protobuf field <code>.bloock.Encrypter encrypter = 3;</code>
     * @param \Bloock\Encrypter $var
     * @return $this
     */
    public function setEncrypter($var)
    {
        GPBUtil::checkMessage($var, \Bloock\Encrypter::class);
        $this->encrypter = $var;

        return $this;
    }

}

