<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.GetCredentialOfferRequest</code>
 */
class GetCredentialOfferRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     */
    protected $config_data = null;
    /**
     * Generated from protobuf field <code>string credential_id = 2;</code>
     */
    protected $credential_id = '';
    /**
     * Generated from protobuf field <code>.bloock.Key key = 3;</code>
     */
    protected $key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bloock\ConfigData $config_data
     *     @type string $credential_id
     *     @type \Bloock\Key $key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Identity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @return \Bloock\ConfigData|null
     */
    public function getConfigData()
    {
        return $this->config_data;
    }

    public function hasConfigData()
    {
        return isset($this->config_data);
    }

    public function clearConfigData()
    {
        unset($this->config_data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @param \Bloock\ConfigData $var
     * @return $this
     */
    public function setConfigData($var)
    {
        GPBUtil::checkMessage($var, \Bloock\ConfigData::class);
        $this->config_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string credential_id = 2;</code>
     * @return string
     */
    public function getCredentialId()
    {
        return $this->credential_id;
    }

    /**
     * Generated from protobuf field <code>string credential_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCredentialId($var)
    {
        GPBUtil::checkString($var, True);
        $this->credential_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bloock.Key key = 3;</code>
     * @return \Bloock\Key|null
     */
    public function getKey()
    {
        return $this->key;
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * Generated from protobuf field <code>.bloock.Key key = 3;</code>
     * @param \Bloock\Key $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkMessage($var, \Bloock\Key::class);
        $this->key = $var;

        return $this;
    }

}

