<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bloock_keys_entities.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.ManagedCertificateParams</code>
 */
class ManagedCertificateParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bloock.KeyType key_type = 1;</code>
     */
    protected $key_type = 0;
    /**
     * Generated from protobuf field <code>int32 expiration = 2;</code>
     */
    protected $expiration = 0;
    /**
     * Generated from protobuf field <code>.bloock.CertificateSubject subject = 3;</code>
     */
    protected $subject = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $key_type
     *     @type int $expiration
     *     @type \Bloock\CertificateSubject $subject
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BloockKeysEntities::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bloock.KeyType key_type = 1;</code>
     * @return int
     */
    public function getKeyType()
    {
        return $this->key_type;
    }

    /**
     * Generated from protobuf field <code>.bloock.KeyType key_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKeyType($var)
    {
        GPBUtil::checkEnum($var, \Bloock\KeyType::class);
        $this->key_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 expiration = 2;</code>
     * @return int
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>int32 expiration = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkInt32($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bloock.CertificateSubject subject = 3;</code>
     * @return \Bloock\CertificateSubject|null
     */
    public function getSubject()
    {
        return $this->subject;
    }

    public function hasSubject()
    {
        return isset($this->subject);
    }

    public function clearSubject()
    {
        unset($this->subject);
    }

    /**
     * Generated from protobuf field <code>.bloock.CertificateSubject subject = 3;</code>
     * @param \Bloock\CertificateSubject $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkMessage($var, \Bloock\CertificateSubject::class);
        $this->subject = $var;

        return $this;
    }

}

