<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authenticity_entities.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.Signer</code>
 */
class Signer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bloock.SignerAlg alg = 1;</code>
     */
    protected $alg = 0;
    /**
     * Generated from protobuf field <code>.bloock.SignerArgs args = 2;</code>
     */
    protected $args = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $alg
     *     @type \Bloock\SignerArgs $args
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AuthenticityEntities::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bloock.SignerAlg alg = 1;</code>
     * @return int
     */
    public function getAlg()
    {
        return $this->alg;
    }

    /**
     * Generated from protobuf field <code>.bloock.SignerAlg alg = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAlg($var)
    {
        GPBUtil::checkEnum($var, \Bloock\SignerAlg::class);
        $this->alg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.bloock.SignerArgs args = 2;</code>
     * @return \Bloock\SignerArgs|null
     */
    public function getArgs()
    {
        return $this->args;
    }

    public function hasArgs()
    {
        return isset($this->args);
    }

    public function clearArgs()
    {
        unset($this->args);
    }

    /**
     * Generated from protobuf field <code>.bloock.SignerArgs args = 2;</code>
     * @param \Bloock\SignerArgs $var
     * @return $this
     */
    public function setArgs($var)
    {
        GPBUtil::checkMessage($var, \Bloock\SignerArgs::class);
        $this->args = $var;

        return $this;
    }

}

