<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bloock_integrity.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.VerifyRecordsRequest</code>
 */
class VerifyRecordsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     */
    protected $config_data = null;
    /**
     * Generated from protobuf field <code>repeated .bloock.Record records = 2;</code>
     */
    private $records;
    /**
     * Generated from protobuf field <code>optional .bloock.Network network = 3;</code>
     */
    protected $network = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Bloock\ConfigData $config_data
     *     @type array<\Bloock\Record>|\Google\Protobuf\Internal\RepeatedField $records
     *     @type int $network
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BloockIntegrity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @return \Bloock\ConfigData|null
     */
    public function getConfigData()
    {
        return $this->config_data;
    }

    public function hasConfigData()
    {
        return isset($this->config_data);
    }

    public function clearConfigData()
    {
        unset($this->config_data);
    }

    /**
     * Generated from protobuf field <code>.bloock.ConfigData config_data = 1;</code>
     * @param \Bloock\ConfigData $var
     * @return $this
     */
    public function setConfigData($var)
    {
        GPBUtil::checkMessage($var, \Bloock\ConfigData::class);
        $this->config_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.Record records = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>repeated .bloock.Record records = 2;</code>
     * @param array<\Bloock\Record>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bloock\Record::class);
        $this->records = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .bloock.Network network = 3;</code>
     * @return int
     */
    public function getNetwork()
    {
        return isset($this->network) ? $this->network : 0;
    }

    public function hasNetwork()
    {
        return isset($this->network);
    }

    public function clearNetwork()
    {
        unset($this->network);
    }

    /**
     * Generated from protobuf field <code>optional .bloock.Network network = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkEnum($var, \Bloock\Network::class);
        $this->network = $var;

        return $this;
    }

}

