<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bloock_integrity.proto

namespace Bloock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bloock.VerifyProofResponse</code>
 */
class VerifyProofResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string record = 1;</code>
     */
    protected $record = null;
    /**
     * Generated from protobuf field <code>optional .bloock.Error error = 2;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $record
     *     @type \Bloock\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BloockIntegrity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string record = 1;</code>
     * @return string
     */
    public function getRecord()
    {
        return isset($this->record) ? $this->record : '';
    }

    public function hasRecord()
    {
        return isset($this->record);
    }

    public function clearRecord()
    {
        unset($this->record);
    }

    /**
     * Generated from protobuf field <code>optional string record = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRecord($var)
    {
        GPBUtil::checkString($var, True);
        $this->record = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .bloock.Error error = 2;</code>
     * @return \Bloock\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>optional .bloock.Error error = 2;</code>
     * @param \Bloock\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Bloock\Error::class);
        $this->error = $var;

        return $this;
    }

}

