<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bloock_webhook.proto

namespace GPBMetadata;

class BloockWebhook
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\BloockShared::initOnce();
        \GPBMetadata\BloockConfig::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x89\x04\x0A\x14bloock_webhook.proto\x12\x06bloock\x1A\x13bloock_config.proto\"\x96\x01\x0A\x1DVerifyWebhookSignatureRequest\x12'\x0A\x0Bconfig_data\x18\x01 \x01(\x0B2\x12.bloock.ConfigData\x12\x0F\x0A\x07payload\x18\x02 \x01(\x0C\x12\x0E\x0A\x06header\x18\x03 \x01(\x09\x12\x11\x0A\x09secretKey\x18\x04 \x01(\x09\x12\x18\x0A\x10enforceTolerance\x18\x05 \x01(\x08\"_\x0A\x1EVerifyWebhookSignatureResponse\x12\x10\x0A\x08is_valid\x18\x01 \x01(\x08\x12!\x0A\x05error\x18\x02 \x01(\x0B2\x0D.bloock.ErrorH\x00\x88\x01\x01B\x08\x0A\x06_error2y\x0A\x0EWebhookService\x12g\x0A\x16VerifyWebhookSignature\x12%.bloock.VerifyWebhookSignatureRequest\x1A&.bloock.VerifyWebhookSignatureResponseBW\x0A\x1Bcom.bloock.sdk.bridge.protoZ8github.com/bloock/bloock-sdk-go/v2/internal/bridge/protob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

