[package]
name = "bloock-core"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
serde = { version = "1.0.139", features = ["std", "derive"] }
thiserror = "1.0.31"
serde_json = "1.0.82"
cfg-if = "1.0.0"
hex = "0.4.3"
bitvec = "1"
bloock-hashing = { path = "../bloock-libs/hashing", version = "=0.1.0" }
bloock-http = { path = "../bloock-libs/http", version = "=0.1.0" }
bloock-web3 = { path = "../bloock-libs/web3", version = "=0.1.0" }

[dev-dependencies]
mockall = "0.11.2"
tokio = { version = "1.20.1", features = ["macros"]}

[dev-dependencies.bloock-http]
path = "../bloock-libs/http"
version = "=0.1.0"
features = ["testing"]

