[package]
name = "bloock-core"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
serde = { version = "1.0.139", features = ["std", "derive"] }
thiserror = "1.0.31"
serde_json = "1.0.82"
cfg-if = "1.0.0"
hex = "0.4.3"
bitvec = "1"
infer = "0.9.0"
base64-url = "1.4.13"
bloock-hasher = { path = "../bloock-libs/hasher" }
bloock-signer = { path = "../bloock-libs/signer" }
bloock-encrypter = { path = "../bloock-libs/encrypter" }
bloock-publisher = { path = "../bloock-libs/publisher" }
bloock-http = { path = "../bloock-libs/http" }
bloock-web3 = { path = "../bloock-libs/web3" }

[dev-dependencies]
mockall = "0.11.2"
tokio = { version = "1.20.1", features = ["rt", "macros"]}
bloock-publisher = { path = "../bloock-libs/publisher", features = ["testing"] }

[dev-dependencies.bloock-http]
path = "../bloock-libs/http"
version = "=0.1.0"
features = ["testing"]

