[workspace]

members = [
    "bloock-core",
    "bloock-c-api",
    "bloock-wasm-api",
    "bloock-libs/hashing",
    "bloock-libs/http",
    "bloock-libs/web3",
]

exclude = []

[profile.release]
debug = false

[profile.bench]
debug = true