[package]
name = "bloock-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.56"
serde = { version = "1.0.123", features = ["std", "derive"] }
thiserror = "1.0.31"
reqwest = { version = "0.11.11", features = ["json", "blocking"] }
serde_json = "1.0.82"
hex = "0.4.3"

[dependencies.tiny-keccak]
version = "2.0.2"
features = ["keccak"]

[dev-dependencies]
mockall = "0.9.1"