[package]
name = "bloock-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"

[dependencies.tiny-keccak]
version = "2.0.2"
features = ["keccak"]

[dev-dependencies]
mockall = "0.9.1"