[workspace]

members = [
    "bloock-core",
    "bloock-bridge",
    "bloock-libs/executor",
    "bloock-libs/hashing",
    "bloock-libs/http",
    "bloock-libs/web3",
    "bloock-libs/builder"
]

exclude = []

[profile.release]
debug = false

[profile.bench]
debug = true