[build]
pre-build = [
    "apt-get update && apt-get install unzip",
    "PROTOC_ZIP=protoc-22.3-linux-x86_64.zip",
    "curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v22.3/$PROTOC_ZIP",
    "unzip -o $PROTOC_ZIP -d /usr/local bin/protoc",
    "unzip -o $PROTOC_ZIP -d /usr/local 'include/*'",
    "rm -f $PROTOC_ZIP",
    "protoc --version"
]

[target.*]
image = ":main"
