[build]
pre-build = [
    "apt-get update && apt-get install unzip",
    "PROTOC_ZIP=protoc-22.3-linux-x86_64.zip",
    "curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v22.3/$PROTOC_ZIP",
    "unzip -o $PROTOC_ZIP -d /usr/local bin/protoc",
    "unzip -o $PROTOC_ZIP -d /usr/local 'include/*'",
    "rm -f $PROTOC_ZIP",
    "protoc --version"
]

[target.x86_64-unknown-linux-gnu]
image = ":main"

[target.x86_64-unknown-linux-musl]
image = ":main"

[target.aarch64-unknown-linux-gnu]
image = ":main"

[target.aarch64-unknown-linux-musl]
image = ":main"

[target.aarch64-linux-android]
image = ":main"

[target.i686-linux-android]
image = ":main"

[target.armv7-linux-androideabi]
image = ":main"

[target.x86_64-linux-android]
image = ":main"

[target.x86_64-pc-windows-gnu]
image = ":main"

[target.x86_64-pc-windows-msvc]
image = ":main"

[target.x86_64-apple-darwin]
image = ":main"

[target.aarch64-apple-darwin]
image = ":main"
