name: "Setup PHP"
description: "Setup PHP"
inputs:
  version:
    required: true
    description: PHP version
  working-directory:
    required: true
    description: Working directory
runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.version }}
        coverage: none
        extensions: ffi
    - name: Install composer dependencies
      uses: ramsey/composer-install@v2
      with:
        working-directory: ${{ inputs.working-directory }}
