name: "Release Zip"
description: "Upload lib to release"
inputs:
  release_url:
    required: true
    description: "Release URL"
  version:
    required: true
    description: "Version number"
  artifact:
    required: true
    description: "Artifact name"
  github_token:
    required: true
    description: "Github token"
runs:
  using: "composite"
  steps:
    - name: Download lib
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
    - name: Compress
      shell: bash
      run: zip -r ${{ inputs.artifact }}.zip ${{ inputs.artifact }}/
    - name: Compress docs
      if: startsWith(inputs.artifact, 'bloock_lib') && !contains(inputs.artifact, 'python_wheels')
      shell: bash
      run: zip -r ${{ inputs.artifact }}-docs.zip ${{ inputs.artifact }}/docs
    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ inputs.release_url }}
        asset_path: ./${{ inputs.artifact }}.zip
        asset_name: ${{ inputs.artifact }}-${{ inputs.version }}.zip
        asset_content_type: application/zip
    - name: Upload docs
      if: startsWith(inputs.artifact, 'bloock_lib') && !contains(inputs.artifact, 'python_wheels')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ inputs.release_url }}
        asset_path: ./${{ inputs.artifact }}-docs.zip
        asset_name: ${{ inputs.artifact }}-docs-${{ inputs.version }}.zip
        asset_content_type: application/zip
