name: "Setup Java"
description: "Setup Java"
inputs:
  version:
    required: true
    description: Java version
  working-directory:
    required: true
    description: Working directory
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.version }}
    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew
      working-directory: ${{ inputs.working-directory }}
