FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest

RUN apt-get update && apt-get install unzip
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protoc-21.5-linux-aarch_64.zip
RUN unzip protoc-21.5-linux-aarch_64.zip -d $HOME/.local 
RUN export PATH="$PATH:$HOME/.local/bin"