FROM ghcr.io/cross-rs/i686-unknown-linux-gnu:latest

RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protoc-21.5-linux-x86_32.zip
RUN unzip protoc-21.5-linux-x86_32.zip -d $HOME/.local 
RUN export PATH="$PATH:$HOME/.local/bin"