name: "Setup Python"
description: "Setup Python"
inputs:
  version:
    required: true
    description: Python version
  working-directory:
    required: true
    description: Working directory
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.version }}
 