name: "Setup Python"
description: "Setup Python"
inputs:
  version:
    required: true
    description: Python version
  working-directory:
    required: true
    description: Working directory
  wheel-version:
    required: false
    description: Wheel version
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.version }}
    - name: Download python wheels from package run
      uses: actions/download-artifact@v3
      with:
        name: bloock_lib_python_wheels
        path: ~/bloock_lib_python_wheels
      if: ${{ inputs.wheel-version }}
    - name: Install wheel
      shell: bash
      run: |
        pip install bloock==${{ inputs.wheel-version }} -f ~/bloock_lib_python_wheels --no-deps --no-index
        pip install bloock==${{ inputs.wheel-version }} -f ~/bloock_lib_python_wheels
      working-directory: ${{ inputs.working-directory }}
      if: ${{ inputs.wheel-version }}
 