name: "Setup Python"
description: "Setup Python"
inputs:
  version:
    required: true
    description: Python version
  working-directory:
    required: true
    description: Working directory
  wheel-version:
    required: false
    description: Wheel version
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.version }}
    - name: Install dependencies
      shell: bash
      run: |
        pip install pydoc-markdown pyotp
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: bloock_core_lib_static
    - name: Copy binaries.
      shell: bash
      run: |
        mkdir -p ${{ inputs.working-directory }}/bloock/_ffi/native
        cp bloock_core_lib_static/bloock_bridge.h ${{ inputs.working-directory }}/bloock/_ffi/native/bloock_bridge.h || true
        
        mkdir -p ${{ inputs.working-directory }}/bloock/_ffi/native/x86_64-unknown-linux-musl
        cp bloock_core_lib_static/x86_64-unknown-linux-musl/libbloock_bridge.a ${{ inputs.working-directory }}/bloock/_ffi/native/x86_64-unknown-linux-musl/libbloock_bridge.a || true
        
        mkdir -p ${{ inputs.working-directory }}/bloock/_ffi/native/aarch64-unknown-linux-musl
        cp bloock_core_lib_static/aarch64-unknown-linux-musl/libbloock_bridge.a ${{ inputs.working-directory }}/bloock/_ffi/native/aarch64-unknown-linux-musl/libbloock_bridge.a || true
        
        mkdir -p ${{ inputs.working-directory }}/bloock/_ffi/native/x86_64-pc-windows-msvc
        cp bloock_core_lib_static/x86_64-pc-windows-msvc/bloock_bridge.lib ${{ inputs.working-directory }}/bloock/_ffi/native/x86_64-pc-windows-msvc/bloock_bridge.lib || true
        
        mkdir -p ${{ inputs.working-directory }}/bloock/_ffi/native/x86_64-apple-darwin
        cp bloock_core_lib_static/x86_64-apple-darwin/libbloock_bridge.a ${{ inputs.working-directory }}/bloock/_ffi/native/x86_64-apple-darwin/libbloock_bridge.a || true
        
        mkdir -p ${{ inputs.working-directory }}/bloock/_ffi/native/aarch64-apple-darwin
        cp bloock_core_lib_static/aarch64-apple-darwin/libbloock_bridge.a ${{ inputs.working-directory }}/bloock/_ffi/native/aarch64-apple-darwin/libbloock_bridge.a || true

    - name: Download python wheels from package run
      uses: actions/download-artifact@v4
      with:
        name: bloock_lib_python
        path: ~/bloock_lib_python
      if: ${{ inputs.wheel-version }}
    - name: Download python wheels from package run
      uses: actions/download-artifact@v4
      with:
        name: bloock_lib_python_wheels
        path: ~/bloock_lib_python/wheelhouse
      if: ${{ inputs.wheel-version }}
    - name: Install wheel
      shell: bash
      run: |
        pip install bloock==${{ inputs.wheel-version }} -f ~/bloock_lib_python/wheelhouse --no-deps --no-index
        pip install bloock==${{ inputs.wheel-version }} -f ~/bloock_lib_python/wheelhouse
      working-directory: ${{ inputs.working-directory }}
      if: ${{ inputs.wheel-version }}
 