// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: authenticity_entities.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignerAlg int32

const (
	SignerAlg_ES256K SignerAlg = 0
	SignerAlg_ENS    SignerAlg = 1
)

// Enum value maps for SignerAlg.
var (
	SignerAlg_name = map[int32]string{
		0: "ES256K",
		1: "ENS",
	}
	SignerAlg_value = map[string]int32{
		"ES256K": 0,
		"ENS":    1,
	}
)

func (x SignerAlg) Enum() *SignerAlg {
	p := new(SignerAlg)
	*p = x
	return p
}

func (x SignerAlg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignerAlg) Descriptor() protoreflect.EnumDescriptor {
	return file_authenticity_entities_proto_enumTypes[0].Descriptor()
}

func (SignerAlg) Type() protoreflect.EnumType {
	return &file_authenticity_entities_proto_enumTypes[0]
}

func (x SignerAlg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignerAlg.Descriptor instead.
func (SignerAlg) EnumDescriptor() ([]byte, []int) {
	return file_authenticity_entities_proto_rawDescGZIP(), []int{0}
}

type Signer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alg  SignerAlg   `protobuf:"varint,1,opt,name=alg,proto3,enum=bloock.SignerAlg" json:"alg,omitempty"`
	Args *SignerArgs `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *Signer) Reset() {
	*x = Signer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticity_entities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signer) ProtoMessage() {}

func (x *Signer) ProtoReflect() protoreflect.Message {
	mi := &file_authenticity_entities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signer.ProtoReflect.Descriptor instead.
func (*Signer) Descriptor() ([]byte, []int) {
	return file_authenticity_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Signer) GetAlg() SignerAlg {
	if x != nil {
		return x.Alg
	}
	return SignerAlg_ES256K
}

func (x *Signer) GetArgs() *SignerArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

type SignerArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey *string `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3,oneof" json:"private_key,omitempty"`
	CommonName *string `protobuf:"bytes,2,opt,name=common_name,json=commonName,proto3,oneof" json:"common_name,omitempty"`
}

func (x *SignerArgs) Reset() {
	*x = SignerArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticity_entities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignerArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerArgs) ProtoMessage() {}

func (x *SignerArgs) ProtoReflect() protoreflect.Message {
	mi := &file_authenticity_entities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerArgs.ProtoReflect.Descriptor instead.
func (*SignerArgs) Descriptor() ([]byte, []int) {
	return file_authenticity_entities_proto_rawDescGZIP(), []int{1}
}

func (x *SignerArgs) GetPrivateKey() string {
	if x != nil && x.PrivateKey != nil {
		return *x.PrivateKey
	}
	return ""
}

func (x *SignerArgs) GetCommonName() string {
	if x != nil && x.CommonName != nil {
		return *x.CommonName
	}
	return ""
}

type Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature   string           `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Protected   string           `protobuf:"bytes,2,opt,name=protected,proto3" json:"protected,omitempty"`
	Header      *SignatureHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	MessageHash string           `protobuf:"bytes,4,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
}

func (x *Signature) Reset() {
	*x = Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticity_entities_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_authenticity_entities_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_authenticity_entities_proto_rawDescGZIP(), []int{2}
}

func (x *Signature) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Signature) GetProtected() string {
	if x != nil {
		return x.Protected
	}
	return ""
}

func (x *Signature) GetHeader() *SignatureHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Signature) GetMessageHash() string {
	if x != nil {
		return x.MessageHash
	}
	return ""
}

type SignatureHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alg string `protobuf:"bytes,1,opt,name=alg,proto3" json:"alg,omitempty"`
	Kid string `protobuf:"bytes,2,opt,name=kid,proto3" json:"kid,omitempty"`
}

func (x *SignatureHeader) Reset() {
	*x = SignatureHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticity_entities_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignatureHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureHeader) ProtoMessage() {}

func (x *SignatureHeader) ProtoReflect() protoreflect.Message {
	mi := &file_authenticity_entities_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureHeader.ProtoReflect.Descriptor instead.
func (*SignatureHeader) Descriptor() ([]byte, []int) {
	return file_authenticity_entities_proto_rawDescGZIP(), []int{3}
}

func (x *SignatureHeader) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *SignatureHeader) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

var File_authenticity_entities_proto protoreflect.FileDescriptor

var file_authenticity_entities_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62,
	0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x22, 0x55, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12,
	0x23, 0x0a, 0x03, 0x61, 0x6c, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x62,
	0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x6c, 0x67, 0x52,
	0x03, 0x61, 0x6c, 0x67, 0x12, 0x26, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x78, 0x0a, 0x0a,
	0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01,
	0x12, 0x24, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x9b, 0x01, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x12, 0x2f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x62, 0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x22, 0x35, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x69, 0x64, 0x2a, 0x20, 0x0a, 0x09, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x41, 0x6c, 0x67, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x53, 0x32, 0x35,
	0x36, 0x4b, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x4e, 0x53, 0x10, 0x01, 0x42, 0x57, 0x0a,
	0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2e, 0x73, 0x64, 0x6b, 0x2e,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x38, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2f,
	0x62, 0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x76, 0x32,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authenticity_entities_proto_rawDescOnce sync.Once
	file_authenticity_entities_proto_rawDescData = file_authenticity_entities_proto_rawDesc
)

func file_authenticity_entities_proto_rawDescGZIP() []byte {
	file_authenticity_entities_proto_rawDescOnce.Do(func() {
		file_authenticity_entities_proto_rawDescData = protoimpl.X.CompressGZIP(file_authenticity_entities_proto_rawDescData)
	})
	return file_authenticity_entities_proto_rawDescData
}

var file_authenticity_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authenticity_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_authenticity_entities_proto_goTypes = []interface{}{
	(SignerAlg)(0),          // 0: bloock.SignerAlg
	(*Signer)(nil),          // 1: bloock.Signer
	(*SignerArgs)(nil),      // 2: bloock.SignerArgs
	(*Signature)(nil),       // 3: bloock.Signature
	(*SignatureHeader)(nil), // 4: bloock.SignatureHeader
}
var file_authenticity_entities_proto_depIdxs = []int32{
	0, // 0: bloock.Signer.alg:type_name -> bloock.SignerAlg
	2, // 1: bloock.Signer.args:type_name -> bloock.SignerArgs
	4, // 2: bloock.Signature.header:type_name -> bloock.SignatureHeader
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_authenticity_entities_proto_init() }
func file_authenticity_entities_proto_init() {
	if File_authenticity_entities_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authenticity_entities_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authenticity_entities_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignerArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authenticity_entities_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authenticity_entities_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignatureHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_authenticity_entities_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authenticity_entities_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authenticity_entities_proto_goTypes,
		DependencyIndexes: file_authenticity_entities_proto_depIdxs,
		EnumInfos:         file_authenticity_entities_proto_enumTypes,
		MessageInfos:      file_authenticity_entities_proto_msgTypes,
	}.Build()
	File_authenticity_entities_proto = out.File
	file_authenticity_entities_proto_rawDesc = nil
	file_authenticity_entities_proto_goTypes = nil
	file_authenticity_entities_proto_depIdxs = nil
}
