// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: availability_entities.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataAvailabilityType int32

const (
	DataAvailabilityType_HOSTED DataAvailabilityType = 0
	DataAvailabilityType_IPFS   DataAvailabilityType = 1
)

// Enum value maps for DataAvailabilityType.
var (
	DataAvailabilityType_name = map[int32]string{
		0: "HOSTED",
		1: "IPFS",
	}
	DataAvailabilityType_value = map[string]int32{
		"HOSTED": 0,
		"IPFS":   1,
	}
)

func (x DataAvailabilityType) Enum() *DataAvailabilityType {
	p := new(DataAvailabilityType)
	*p = x
	return p
}

func (x DataAvailabilityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataAvailabilityType) Descriptor() protoreflect.EnumDescriptor {
	return file_availability_entities_proto_enumTypes[0].Descriptor()
}

func (DataAvailabilityType) Type() protoreflect.EnumType {
	return &file_availability_entities_proto_enumTypes[0]
}

func (x DataAvailabilityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataAvailabilityType.Descriptor instead.
func (DataAvailabilityType) EnumDescriptor() ([]byte, []int) {
	return file_availability_entities_proto_rawDescGZIP(), []int{0}
}

type Publisher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type DataAvailabilityType `protobuf:"varint,1,opt,name=type,proto3,enum=bloock.DataAvailabilityType" json:"type,omitempty"`
	Args *PublisherArgs       `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *Publisher) Reset() {
	*x = Publisher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_entities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Publisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publisher) ProtoMessage() {}

func (x *Publisher) ProtoReflect() protoreflect.Message {
	mi := &file_availability_entities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publisher.ProtoReflect.Descriptor instead.
func (*Publisher) Descriptor() ([]byte, []int) {
	return file_availability_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Publisher) GetType() DataAvailabilityType {
	if x != nil {
		return x.Type
	}
	return DataAvailabilityType_HOSTED
}

func (x *Publisher) GetArgs() *PublisherArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

type PublisherArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublisherArgs) Reset() {
	*x = PublisherArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_entities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublisherArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherArgs) ProtoMessage() {}

func (x *PublisherArgs) ProtoReflect() protoreflect.Message {
	mi := &file_availability_entities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherArgs.ProtoReflect.Descriptor instead.
func (*PublisherArgs) Descriptor() ([]byte, []int) {
	return file_availability_entities_proto_rawDescGZIP(), []int{1}
}

type Loader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type DataAvailabilityType `protobuf:"varint,1,opt,name=type,proto3,enum=bloock.DataAvailabilityType" json:"type,omitempty"`
	Args *LoaderArgs          `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *Loader) Reset() {
	*x = Loader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_entities_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Loader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loader) ProtoMessage() {}

func (x *Loader) ProtoReflect() protoreflect.Message {
	mi := &file_availability_entities_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loader.ProtoReflect.Descriptor instead.
func (*Loader) Descriptor() ([]byte, []int) {
	return file_availability_entities_proto_rawDescGZIP(), []int{2}
}

func (x *Loader) GetType() DataAvailabilityType {
	if x != nil {
		return x.Type
	}
	return DataAvailabilityType_HOSTED
}

func (x *Loader) GetArgs() *LoaderArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

type LoaderArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LoaderArgs) Reset() {
	*x = LoaderArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_availability_entities_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoaderArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoaderArgs) ProtoMessage() {}

func (x *LoaderArgs) ProtoReflect() protoreflect.Message {
	mi := &file_availability_entities_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoaderArgs.ProtoReflect.Descriptor instead.
func (*LoaderArgs) Descriptor() ([]byte, []int) {
	return file_availability_entities_proto_rawDescGZIP(), []int{3}
}

func (x *LoaderArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_availability_entities_proto protoreflect.FileDescriptor

var file_availability_entities_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62,
	0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x22, 0x68, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x62, 0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22,
	0x0f, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73,
	0x22, 0x62, 0x0a, 0x06, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x62, 0x6c, 0x6f, 0x6f, 0x63,
	0x6b, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x6c, 0x6f,
	0x6f, 0x63, 0x6b, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x41, 0x72, 0x67, 0x73, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x22, 0x1c, 0x0a, 0x0a, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x41, 0x72,
	0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x2a, 0x2c, 0x0a, 0x14, 0x44, 0x61, 0x74, 0x61, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x4f,
	0x53, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x50, 0x46, 0x53, 0x10, 0x01,
	0x42, 0x57, 0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2e, 0x73,
	0x64, 0x6b, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5a,
	0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x6f,
	0x63, 0x6b, 0x2f, 0x62, 0x6c, 0x6f, 0x6f, 0x63, 0x6b, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f,
	0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_availability_entities_proto_rawDescOnce sync.Once
	file_availability_entities_proto_rawDescData = file_availability_entities_proto_rawDesc
)

func file_availability_entities_proto_rawDescGZIP() []byte {
	file_availability_entities_proto_rawDescOnce.Do(func() {
		file_availability_entities_proto_rawDescData = protoimpl.X.CompressGZIP(file_availability_entities_proto_rawDescData)
	})
	return file_availability_entities_proto_rawDescData
}

var file_availability_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_availability_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_availability_entities_proto_goTypes = []interface{}{
	(DataAvailabilityType)(0), // 0: bloock.DataAvailabilityType
	(*Publisher)(nil),         // 1: bloock.Publisher
	(*PublisherArgs)(nil),     // 2: bloock.PublisherArgs
	(*Loader)(nil),            // 3: bloock.Loader
	(*LoaderArgs)(nil),        // 4: bloock.LoaderArgs
}
var file_availability_entities_proto_depIdxs = []int32{
	0, // 0: bloock.Publisher.type:type_name -> bloock.DataAvailabilityType
	2, // 1: bloock.Publisher.args:type_name -> bloock.PublisherArgs
	0, // 2: bloock.Loader.type:type_name -> bloock.DataAvailabilityType
	4, // 3: bloock.Loader.args:type_name -> bloock.LoaderArgs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_availability_entities_proto_init() }
func file_availability_entities_proto_init() {
	if File_availability_entities_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_availability_entities_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Publisher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_entities_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublisherArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_entities_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Loader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_availability_entities_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoaderArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_availability_entities_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_availability_entities_proto_goTypes,
		DependencyIndexes: file_availability_entities_proto_depIdxs,
		EnumInfos:         file_availability_entities_proto_enumTypes,
		MessageInfos:      file_availability_entities_proto_msgTypes,
	}.Build()
	File_availability_entities_proto = out.File
	file_availability_entities_proto_rawDesc = nil
	file_availability_entities_proto_goTypes = nil
	file_availability_entities_proto_depIdxs = nil
}
