[package]
name = "bloock-encrypter"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
serde = { version = "1.0.123", features = ["std", "derive"] }
thiserror = "1.0.31"
aes-gcm = "0.10"
rand = "0.6"
base64 = "0.13"
hex = "0.4.3"
