name: Build PHP

on:
  workflow_call:

jobs:
  build_wheel:
    name: Build PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download static libs
        uses: actions/download-artifact@v1
        with:
          name: bloock_core_lib_static
      - name: Copy library headers.
        run: |
          mkdir -p languages/php/Bloock/Ffi/native
          cp -r bloock_core_lib_static/bloock_bridge.h languages/php/Bloock/Ffi/native/bloock_bridge.h
      - name: Copy static library.
        if: runner.os == 'Linux'
        run: |
          cp -r bloock_core_lib_static/libbloock_bridge_x86_64-unknown-linux-musl.a languages/php/Bloock/Ffi/native/libbloock_bridge.a
      - name: Copy static library.
        if: runner.os == 'macOS'
        run: |
          cp -r bloock_core_lib_static/libbloock_bridge-fat.a languages/php/Bloock/Ffi/native/libbloock_bridge.a
      - name: Copy static library.
        if: runner.os == 'Windows'
        run: |
          cp -r bloock_core_lib_static/bloock_bridge_windows.lib languages/php/Bloock/Ffi/native/libbloock_bridge.lib
      - name: Copy in readme
        run: |
          cp README.md languages/php/README.md
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_lib_php
          path: languages/php
