name: Build Java

on:
  workflow_call:

jobs:
  build_java:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set version env
        id: version
        shell: bash
        run: echo "bloock_version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v1
        with:
          java-version: "10"
      - name: Download binaries
        uses: actions/download-artifact@v1
        with:
          name: bloock_core_lib_dynamic
      - name: Copy binaries.
        run: |
          mkdir -p languages/java/src/main/resources
          cp -r bloock_core_lib_dynamic/* languages/java/src/main/resources/
      - name: Cleanup
        run: |
          rm languages/java/Makefile
          cp LICENSE languages/java/LICENSE
          cp README.md languages/java/README.md
      - name: Build
        run: |
          ./gradlew build -x test
          ./gradlew shadowJar
        working-directory: languages/java
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_lib_java
          path: languages/java
