name: Build WASM

on:
  workflow_call:

jobs:
  build_wasm:
    name: Build lib WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-wasm-build-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build release libraries
        run: make -C bloock-bridge build-wasm
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_core_lib_wasm
          if-no-files-found: error
          path: |
            bloock-bridge/build/wasm
