name: Build Python

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build_wheel:
    name: Build wheel
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Download binaries
        uses: actions/download-artifact@v1
        with:
          name: bloock_core_lib_static
      - name: Copy binaries.
        run: |
          mkdir -p languages/python/bloock/_ffi/native
          cp -r bloock_core_lib_static/* languages/python/bloock/_ffi/native/
      - name: Cleanup
        run: |
          rm languages/python/Makefile
          cp LICENSE languages/python/LICENSE
          cp README.md languages/python/README.md
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: "*64"
          CIBW_ENVIRONMENT: BLOOCK_ENV=CI
          CIBW_ARCHS: "${{ inputs.os == 'macos-latest' && 'x86_64 arm64 universal2' || 'auto' }}"
        with:
          package-dir: languages/python
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_lib_python
          path: ./wheelhouse/*.whl
