name: Build Linux

on:
  workflow_call:

jobs:
  build_linux:
    name: Build lib Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build release libraries
        run: make -C bloock-bridge x86_64-unknown-linux-gnu
      - name: Install musl tools
        run: sudo apt-get install musl-tools
      - name: Install rustup musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build release musl libraries
        run: RUSTFLAGS="-C target-feature=-crt-static" make -C bloock-bridge x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_library
          if-no-files-found: error
          path: |
            bloock-bridge/build/native/bloock_bridge.h
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_library
          if-no-files-found: error
          path: |
            bloock-bridge/build/native/x86_64-unknown-linux-gnu/libbloock_bridge.so
            bloock-bridge/build/native/x86_64-unknown-linux-musl/libbloock_bridge.so
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_static_library
          if-no-files-found: error
          path: |
            bloock-bridge/build/native/x86_64-unknown-linux-gnu/libbloock_bridge.so
            bloock-bridge/build/native/x86_64-unknown-linux-musl/libbloock_bridge.a
