name: Build Java

on:
  workflow_call:

jobs:
  build_java:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_java
        with:
          version: 10
          working-directory: languages/java
      - name: Cleanup
        run: |
          cp LICENSE languages/java/LICENSE
          cp README.md languages/java/README.md
      - name: Build
        run: |
          ./gradlew jar
          ./gradlew shadowJar
        working-directory: languages/java
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_lib_java
          path: languages/java
