name: Build Linux

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      target:
        required: true
        type: string
      cargo_command:
        required: true
        type: string

jobs:
  build:
    name: Build for ${{ inputs.target }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ inputs.target }}-rust-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain if not cross-compiling
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ inputs.target }}
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !inputs.cross }}
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ contains(inputs.cargo_command, 'cross') }}
          command: build
          args: --locked --release --target ${{ inputs.target }}
      - name: Copy binaries (Linux)
        run: |
          mkdir -p bloock-bridge/build/native/${{ inputs.target }}
          cp target/${{ inputs.target }}/release/libbloock_bridge.a bloock-bridge/build/native/${{ inputs.target }} | true
          cp target/${{ inputs.target }}/release/libbloock_bridge.so bloock-bridge/build/native/${{ inputs.target }} | true
        if: contains(inputs.target, 'linux')
      - name: Copy binaries (Windows)
        run: |
          mkdir -p bloock-bridge/build/native/${{ inputs.target }}
          cp target/${{ inputs.target }}/release/bloock_bridge.a bloock-bridge/build/native/${{ inputs.target }} | true
          cp target/${{ inputs.target }}/release/bloock_bridge.dll bloock-bridge/build/native/${{ inputs.target }} | true
        if: contains(inputs.target, 'windows')
      - name: Copy binaries (Darwin)
        run: |
          mkdir -p bloock-bridge/build/native/${{ inputs.target }}
          cp target/${{ inputs.target }}/release/libbloock_bridge.a bloock-bridge/build/native/${{ inputs.target }} | true
          cp target/${{ inputs.target }}/release/libbloock_bridge.dylib bloock-bridge/build/native/${{ inputs.target }} | true
        if: contains(inputs.target, 'darwin')
      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bloock_core_lib
          if-no-files-found: error
          path: |
            bloock-bridge/build/native/*
