name: Build Python

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build_wheel:
    name: Build wheel
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Download static libs
        uses: actions/download-artifact@v1
        with:
          name: bloock_core_lib_static
      - name: Copy static library.
        run: |
          mkdir -p languages/python/bloock/native
          cp -r bloock_core_lib_static/libbloock_bridge_x86_64-unknown-linux-musl.a languages/python/bloock/_ffi/native/libbloock_bridge.a
          cp -r bloock_core_lib_static/bloock_bridge.h languages/python/bloock/_ffi/native/bloock_bridge.h
      - name: Copy in readme
        run: |
          cp README.md languages/python/bloock/README.md
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_BUILD: "*64"
          CIBW_ARCHS: "${{ inputs.os == 'macos-latest' && 'x86_64 arm64 universal2' || 'auto' }}"
        with:
          package-dir: languages/python/bloock
      - uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: ./wheelhouse/*.whl
