name: Build Python

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build_wheel:
    name: Build wheel
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Download binaries
        uses: actions/download-artifact@v1
        with:
          name: bloock_core_lib_static
      - name: Copy binaries.
        run: |
          mkdir -p languages/python/bloock/_ffi/native
          [[ -e bloock_core_lib_static/bloock_bridge.h ]] && cp bloock_core_lib_static/bloock_bridge.h languages/python/bloock/_ffi/native/bloock_bridge.h
          
          mkdir -p languages/python/bloock/_ffi/native/x86_64-unknown-linux-musl
          [[ -e bloock_core_lib_static/x86_64-unknown-linux-musl/libbloock_bridge.a ]] && cp bloock_core_lib_static/x86_64-unknown-linux-musl/libbloock_bridge.a languages/python/bloock/_ffi/native/x86_64_unknown_linux_musl/libbloock_bridge.a
          
          mkdir -p languages/python/bloock/_ffi/native/aarch64-unknown-linux-gnu
          [[ -e bloock_core_lib_static/aarch64-unknown-linux-gnu/libbloock_bridge.a ]] && cp bloock_core_lib_static/aarch64-unknown-linux-gnu/libbloock_bridge.a languages/python/bloock/_ffi/native/aarch64_unknown_linux_musl/libbloock_bridge.a
          
          mkdir -p languages/python/bloock/_ffi/native/x86_64-pc-windows-gnu
          [[ -e bloock_core_lib_static/x86_64-pc-windows-gnu/libbloock_bridge.a ]] && cp bloock_core_lib_static/x86_64-pc-windows-gnu/libbloock_bridge.a languages/python/bloock/_ffi/native/x86_64_pc_windows_gnu/libbloock_bridge_windows.a
          
          mkdir -p languages/python/bloock/_ffi/native/x86_64-apple-darwin
          [[ -e bloock_core_lib_static/x86_64-apple-darwin/libbloock_bridge.a ]] && cp bloock_core_lib_static/x86_64-apple-darwin/libbloock_bridge.a languages/python/bloock/_ffi/native/x86_64_apple_darwin/libbloock_bridge.a
          
          mkdir -p languages/python/bloock/_ffi/native/aarch64-apple-darwin
          [[ -e bloock_core_lib_static/aarch64-apple-darwin/libbloock_bridge.a ]] && cp bloock_core_lib_static/aarch64-apple-darwin/libbloock_bridge.a languages/python/bloock/_ffi/native/aarch64_apple_darwin/libbloock_bridge.a

      - name: Cleanup
        run: |
          cp LICENSE languages/python/LICENSE
          cp README.md languages/python/README.md
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: "*64"
          CIBW_ARCHS: "${{ inputs.os == 'macos-latest' && 'x86_64 arm64 universal2' || 'auto' }}"
        with:
          package-dir: languages/python
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_lib_python
          path: ./wheelhouse/*.whl
