name: Build Linux

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build_linux:
    name: Build lib Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install arm tools
        if: ${{ inputs.target }} == 'aarch64-unknown-linux-gnu' || ${{ inputs.target }} == 'aarch64-unknown-linux-musl'
        run: |
          sudo apt-get install clang llvm
      - name: Install musl tools
        if: ${{ inputs.target }} == 'x86_64-unknown-linux-musl' || ${{ inputs.target }} == 'aarch64-unknown-linux-musl'
        run: |
          sudo apt-get install musl-tools
      - name: Install rustup target
        run: rustup target add ${{ inputs.target }}
      - name: Build release libraries
        run: |
          export CC_aarch64_unknown_linux_musl=clang
          export AR_aarch64_unknown_linux_musl=llvm-ar
          export CFLAGS_aarch64_unknown_linux_musl="--sysroot=/usr/aarch64-linux-musl"
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS="-Clink-self-contained=yes -Clinker=rust-lld"
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUNNER="qemu-aarch64 -L /usr/aarch64-linux-musl"

          export CC_aarch64_unknown_linux_gnu=clang
          export AR_aarch64_unknown_linux_gnu=llvm-ar
          export CFLAGS_aarch64_unknown_linux_gnu="--sysroot=/usr/aarch64-linux-gnu"
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUSTFLAGS="-Clink-self-contained=yes -Clinker=rust-lld"
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER="qemu-aarch64 -L /usr/aarch64-linux-gnu"

          make -C bloock-bridge ${{ inputs.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_library
          if-no-files-found: error
          path: |
            bloock-bridge/build/native/bloock_bridge.h
            bloock-bridge/build/native/${{ inputs.target }}/libbloock_bridge.so
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_static_library
          if-no-files-found: error
          path: |
            bloock-bridge/build/native/bloock_bridge.h
            bloock-bridge/build/native/${{ inputs.target }}/libbloock_bridge.a
