name: Build Linux

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build_linux:
    name: Build lib Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install musl tools
        if: ${{ inputs.target }} == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get install musl-tools
          export RUSTFLAGS="-C target-feature=-crt-static"
      - name: Install rustup target
        run: rustup target add ${{ inputs.target }}
      - name: Build release libraries
        run: make -C bloock-bridge ${{ inputs.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_library
          if-no-files-found: error
          path: |
            bloock-bridge/build/native/bloock_bridge.h
            bloock-bridge/build/native/${{ inputs.target }}/libbloock_bridge.so
      - uses: actions/upload-artifact@v2
        with:
          name: bloock_static_library
          if-no-files-found: error
          path: |
            bloock-bridge/build/native/bloock_bridge.h
            bloock-bridge/build/native/${{ inputs.target }}/libbloock_bridge.so
