name: Check JS

on:
  workflow_call:

jobs:
  check_js:
    name: Check JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download bloock js from package run
        uses: actions/download-artifact@v1
        with:
          name: bloock_js_node
      - name: Install production dependencies
        run: yarn install --production
        working-directory: bloock_js_node
      - name: Run tests
        run: yarn test
        working-directory: bloock_js_node
