name: Check Python

on:
  workflow_call:

jobs:
  check_python:
    name: Check Python.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Python formatter
        run: pip install black
      - name: Check Python formatting
        run: black --check languages/python
