name: Check JS

on:
  workflow_call:

jobs:
  check_js:
    name: Check JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Check formatting of JS library
        working-directory: "languages/js"
        run: make fmtcheck
      - name: Add WebAssembly target
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Lint JS library
        working-directory: "languages/js"
        run: make lint
