name: Development
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check_version

  build_binaries:
    needs: [version]
    uses: ./.github/workflows/build_rust.yml
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cargo_command: cross
          
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cargo_command: cross
    with:
      os: ${{ matrix.platform.os }}
      target: ${{ matrix.platform.target }}
      cargo_command: ${{ matrix.platform.cargo_command }}

  build_wasm:
    needs: [version]
    uses: ./.github/workflows/build_wasm.yml

  test_rust:
    needs: [build_binaries, build_wasm]
    uses: ./.github/workflows/test_rust.yml
    strategy:
      matrix:
        os: [ubuntu-latest]
    with:
      os: ${{ matrix.os }}
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_js:
    needs: [build_wasm]
    uses: ./.github/workflows/build_js.yml

  test_js:
    needs: [build_js]
    uses: ./.github/workflows/test_lib.yml
    with:
      artifact: bloock_lib_js
      lang: js
      lang-version: 18
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_go:
    needs: [build_binaries]
    uses: ./.github/workflows/build_go.yml

  test_go:
    needs: [build_go]
    uses: ./.github/workflows/test_lib.yml
    with:
      artifact: bloock_lib_go
      lang: go
      lang-version: 1.19
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_python:
    needs: [build_binaries]
    uses: ./.github/workflows/build_python.yml
    with:
      os: ubuntu-latest

  test_python:
    needs: [build_python]
    uses: ./.github/workflows/test_lib.yml
    with:
      lang: python
      lang-version: 3.10
      artifact: bloock_lib_python
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_java:
    needs: [build_binaries]
    uses: ./.github/workflows/build_java.yml

  test_java:
    needs: [build_java]
    uses: ./.github/workflows/test_lib.yml
    with:
      artifact: bloock_lib_java
      lang: java
      lang-version: 8
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_php:
    needs: [build_binaries]
    uses: ./.github/workflows/build_php.yml

  test_php:
    needs: [build_php]
    uses: ./.github/workflows/test_lib.yml
    with:
      artifact: bloock_lib_php
      lang: php
      lang-version: 8.2
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}
