name: Development
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check_version

  build_binaries:
    needs: [version]
    uses: ./.github/workflows/build_rust.yml
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cargo_command: cross
          
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cargo_command: cross
    with:
      os: ${{ matrix.platform.os }}
      target: ${{ matrix.platform.target }}
      cargo_command: ${{ matrix.platform.cargo_command }}

  build_wasm:
    needs: [version]
    uses: ./.github/workflows/build_wasm.yml

  test_rust:
    needs: [build_binaries, build_wasm]
    uses: ./.github/workflows/test_rust.yml
    strategy:
      matrix:
        os: [ubuntu-latest]
    with:
      os: ${{ matrix.os }}
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_js:
    needs: [build_wasm]
    uses: ./.github/workflows/build_js.yml

  test_js:
    needs: [build_js]
    uses: ./.github/workflows/test_js.yml
    with:
      os: ubuntu-latest
      node-version: 16
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_go:
    needs: [build_binaries]
    uses: ./.github/workflows/build_go.yml

  test_go:
    needs: [build_go]
    uses: ./.github/workflows/test_go.yml
    with:
      os: ubuntu-latest
      go-version: "1.18"
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_python:
    needs: [build_binaries]
    uses: ./.github/workflows/build_python.yml
    with:
      os: ubuntu-latest

  test_python:
    needs: [build_python]
    uses: ./.github/workflows/test_python.yml
    with:
      os: ubuntu-latest
      python-version: "3.7"
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_java:
    needs: [build_binaries]
    uses: ./.github/workflows/build_java.yml

  test_java:
    needs: [build_java]
    uses: ./.github/workflows/test_java.yml
    with:
      os: ubuntu-latest
      java-version: "10"
    secrets:
      api_host: ${{ secrets.API_HOST }}
      api_key: ${{ secrets.API_KEY }}

  build_php:
    needs: [build_binaries]
    uses: ./.github/workflows/build_php.yml

  test_php:
    needs: [build_php]
    uses: ./.github/workflows/test_php.yml
    with:
      os: ubuntu-latest
      php-version: "8.1"
    secrets:
      api_key: ${{ secrets.API_KEY }}
