name: Development
on:
  push:
    branches:
      - feature/EIT-2580

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check_version

  build:
    needs: [version]
    uses: ./.github/workflows/build_linux.yml
    with:
      target: x86_64-unknown-linux-gnu

  check_rust:
    needs: [build]
    uses: ./.github/workflows/check_rust.yml

  test_rust:
    needs: [check_rust]
    uses: ./.github/workflows/test_rust.yml

  check_js:
    needs: [build]
    uses: ./.github/workflows/check_js.yml

  test_js:
    needs: [check_js]
    uses: ./.github/workflows/test_rust.yml

  check_go:
    needs: [build]
    uses: ./.github/workflows/check_go.yml

  test_go:
    needs: [check_go]
    uses: ./.github/workflows/test_rust.yml
