name: Development
on:
  push:
    branches:
      - feature/EIT-2580

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check_version

  check_rust:
    needs: [version]
    uses: ./.github/workflows/check_rust.yml

  build_rust:
    needs: [check_rust]
    uses: ./.github/workflows/build_linux.yml
    with:
      target: x86_64-unknown-linux-gnu

  test_rust:
    needs: [build_rust]
    uses: ./.github/workflows/test_rust.yml

  check_js:
    needs: [build_rust]
    uses: ./.github/workflows/check_js.yml

  build_js:
    needs: [check_js]
    uses: ./.github/workflows/build_js.yml

  test_js:
    needs: [build_js]
    uses: ./.github/workflows/test_js.yml
    with:
      os: ubuntu-latest
      node-version: 16

  check_go:
    needs: [build_rust]
    uses: ./.github/workflows/check_go.yml

  build_go:
    needs: [check_go]
    uses: ./.github/workflows/build_go.yml

  test_go:
    needs: [build_go]
    uses: ./.github/workflows/test_go.yml
    with:
      os: ubuntu-latest
      go-version: 18
