name: Publish JS

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      npm_auth_token:
        required: true

jobs:
  upload_js:
    name: Upload JS
    runs-on: ubuntu-latest
    steps:
      - name: Download bloock js lib
        uses: actions/download-artifact@v1
        with:
          name: bloock_lib_js
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install dependencies
        working-directory: bloock_lib_js
        run: yarn install --frozen-lockfile
      - name: Set up .npmrc
        working-directory: bloock_lib_js
        run: echo '//registry.npmjs.org/:_authToken=${{ secrets.npm_auth_token }}' > .npmrc
      - run: npm publish
        working-directory: bloock_lib_js
