name: Publish Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"
        required: true

jobs:
  mark-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Mark release as latest
        uses: tubone24/update_release@v1.3.1
        with:
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: "v${{ github.event.inputs.version }}"

  publish_go:
    needs: [mark-latest]
    uses: ./.github/workflows/publish_go.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      repo_api_token: ${{ secrets.REPO_API_TOKEN }}

  publish_python:
    needs: [mark-latest]
    uses: ./.github/workflows/publish_python.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      twine_username: ${{ secrets.TWINE_USERNAME }}
      twine_password: ${{ secrets.TWINE_PASSWORD }}

  publish_js:
    needs: [mark-latest]
    uses: ./.github/workflows/publish_js.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN }}

  publish_java:
    needs: [mark-latest]
    uses: ./.github/workflows/publish_java.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      sonatype_username: ${{ secrets.SONATYPE_USERNAME }}
      sonatype_password: ${{ secrets.SONATYPE_PASSWORD }}
      pgp_secret: ${{ secrets.PGP_SECRET }}
      pgp_passphrase: ${{ secrets.PGP_PASSPHRASE }}

  run_quickstarts:
    needs: [publish_go, publish_python, publish_js, publish_java]
    name: Run quickstarts.
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.repo_api_token }}
          repository: bloock/bloock-sdk-quickstart
          event-type: run_quickstarts
          client-payload: '{"version": "${{ github.event.inputs.version }}"}'

