name: Publish Go

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      release_url:
        required: true
        type: string

jobs:
  upload_go:
    name: Upload Go.
    runs-on: ubuntu-latest
    steps:
      - name: Download bloock go lib
        uses: actions/download-artifact@v1
        with:
          name: go
      - name: Zip Go source code
        run: zip -r go-bloock.zip go/
      - name: Upload go package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./go-bloock.zip
          asset_name: go-bloock-${{ inputs.version }}.zip
          asset_content_type: application/zip
