name: Publish Java

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      sonatype_username:
        required: true
      sonatype_password:
        required: true
      pgp_secret:
        required: true
      pgp_passphrase:
        required: true

jobs:
  publish_java:
    name: Publish Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "v${{ github.event.inputs.version }}"
      - name: Download dylibs
        uses: actions/download-artifact@v1
        with:
          name: bloock_core_lib_dynamic
      - name: Copy libraries into resources.
        run: |
          mkdir -p languages/java/src/main/resources/linux
          [[ -e bloock_core_lib_dynamic/libbloock_bridge_x86_64-unknown-linux-musl.so ]] && cp -r bloock_core_lib_dynamic/libbloock_bridge_x86_64-unknown-linux-musl.so languages/java/src/main/resources/linux/libbloock_bridge.so
          mkdir -p languages/java/src/main/resources/macos
          [[ -e bloock_core_lib_dynamic/libbloock_bridge-fat.dylib ]] && cp -r bloock_core_lib_dynamic/libbloock_bridge-fat.dylib languages/java/src/main/resources/macos/libbloock_bridge.dylib
          mkdir -p languages/java/src/main/resources/win
          [[ -e bloock_core_lib_dynamic/bloock_bridge_windows.dll ]] && cp -r bloock_core_lib_dynamic/bloock_bridge_windows.dll languages/java/src/main/resources/win/bloock_bridge.dll
          rm languages/java/Makefile
      - name: Publish with Gradle
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.sonatype_username }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.sonatype_password }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.pgp_secret }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.pgp_passphrase }}
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --no-daemon
        working-directory: languages/java
