name: Publish PHP

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      repo_api_token:
        required: true

jobs:
  upload_php:
    name: Upload PHP.
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.repo_api_token }}
          repository: bloock/bloock-sdk-php
          event-type: bloock_publish
          client-payload: '{"version": "${{ inputs.version }}"}'
