name: Publish Python

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      twine_username:
        required: true
      twine_password:
        required: true

jobs:
  publish_python:
    name: Publish Python
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.twine_username }}
      TWINE_PASSWORD: ${{ secrets.twine_password }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "v${{ github.event.inputs.version }}"
      - run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" $(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/bloock/bloock-sdk/releases/tags/v${{ github.event.inputs.version }} | jq -r '.assets[] | select(.name == "bloock_lib_python-${{ github.event.inputs.version }}.zip") | .url') --output bloock_lib_python-${{ github.event.inputs.version }}.zip
      - run: unzip bloock_lib_python-${{ github.event.inputs.version }}.zip -d bloock_lib_python-${{ github.event.inputs.version }}
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.10"
      - run: pip install twine
      - run: twine upload bloock_lib_python-${{ github.event.inputs.version }}/bloock_lib_python/wheelhouse/*.whl --non-interactive
