name: Create Release
on:
  push:
    tags:
      - "v*"
    branches:
      - master

jobs:
  version:
    name: Compute and verify the version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check_version
      - name: Set version env
        run: echo "bloock_version=$(cat VERSION)" >> $GITHUB_ENV
      - name: Check github ref matches
        if: startsWith(github.ref, 'refs/tags/')
        env:
          github_ref: ${{ github.ref }}
        run: grep "${github_ref/refs\/tags\/v/}" VERSION

  build_binaries:
    needs: [version]
    uses: ./.github/workflows/build_rust.yml
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cargo_command: cross

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cargo_command: cross

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cargo_command: cross

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            cargo_command: cross

          - os: ubuntu-latest
            target: aarch64-linux-android
            cargo_command: cross

          - os: ubuntu-latest
            target: armv7-linux-androideabi
            cargo_command: cross

          - os: ubuntu-latest
            target: i686-linux-android
            cargo_command: cross

          - os: ubuntu-latest
            target: x86_64-linux-android
            cargo_command: cross

          - os: windows-latest
            target: x86_64-pc-windows-gnu
            cargo_command: cargo

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cargo_command: cargo

          - os: macOS-latest
            target: x86_64-apple-darwin
            cargo_command: cargo

          - os: macOS-latest
            target: aarch64-apple-darwin
            cargo_command: cargo
    with:
      os: ${{ matrix.platform.os }}
      target: ${{ matrix.platform.target }}
      cargo_command: ${{ matrix.platform.cargo_command }}

  build_wasm:
    needs: [version]
    uses: ./.github/workflows/build_wasm.yml

  build_go:
    needs: [build_binaries]
    uses: ./.github/workflows/build_lib.yml
    with:
      os: ubuntu-latest
      lang: go
      lang-version: 1.19

  build_python:
    needs: [build_binaries]
    uses: ./.github/workflows/build_python.yml

  build_java:
    needs: [build_binaries]
    uses: ./.github/workflows/build_lib.yml
    with:
      os: ubuntu-latest
      lang: java
      lang-version: 8

  build_php:
    needs: [build_binaries]
    uses: ./.github/workflows/build_lib.yml
    with:
      os: ubuntu-latest
      lang: php
      lang-version: 8.2

  build_js:
    needs: [build_wasm]
    uses: ./.github/workflows/build_lib.yml
    with:
      os: ubuntu-latest
      lang: js
      lang-version: 18

  test_rust:
    needs: [build_binaries, build_wasm]
    uses: ./.github/workflows/test_rust.yml
    with:
      os: ubuntu-latest
    secrets:
      api_host: ${{ secrets.API_HOST }}
      dev_api_host: ${{ secrets.DEV_API_HOST }}
      api_key: ${{ secrets.API_KEY }}
      dev_api_key: ${{ secrets.DEV_API_KEY }}
      dev_identity_api_host: ${{ secrets.DEV_IDENTITY_API_HOST }}

  test_go:
    needs: [build_go]
    uses: ./.github/workflows/test_lib.yml
    with:
      lang: go
      lang-version: 1.19
    secrets:
      api_host: ${{ secrets.API_HOST }}
      dev_api_host: ${{ secrets.DEV_API_HOST }}
      api_key: ${{ secrets.API_KEY }}
      dev_api_key: ${{ secrets.DEV_API_KEY }}
      dev_identity_api_host: ${{ secrets.DEV_IDENTITY_API_HOST }}

  test_python:
    needs: [build_python]
    uses: ./.github/workflows/test_lib.yml
    with:
      lang: python
      lang-version: "3.10"
    secrets:
      api_host: ${{ secrets.API_HOST }}
      dev_api_host: ${{ secrets.DEV_API_HOST }}
      api_key: ${{ secrets.API_KEY }}
      dev_api_key: ${{ secrets.DEV_API_KEY }}
      dev_identity_api_host: ${{ secrets.DEV_IDENTITY_API_HOST }}

  test_java:
    needs: [build_java]
    uses: ./.github/workflows/test_lib.yml
    with:
      lang: java
      lang-version: 8
    secrets:
      api_host: ${{ secrets.API_HOST }}
      dev_api_host: ${{ secrets.DEV_API_HOST }}
      api_key: ${{ secrets.API_KEY }}
      dev_api_key: ${{ secrets.DEV_API_KEY }}
      dev_identity_api_host: ${{ secrets.DEV_IDENTITY_API_HOST }}

  test_php:
    needs: [build_php]
    uses: ./.github/workflows/test_lib.yml
    with:
      lang: php
      lang-version: 8.2
    secrets:
      api_host: ${{ secrets.API_HOST }}
      dev_api_host: ${{ secrets.DEV_API_HOST }}
      api_key: ${{ secrets.API_KEY }}
      dev_api_key: ${{ secrets.DEV_API_KEY }}
      dev_identity_api_host: ${{ secrets.DEV_IDENTITY_API_HOST }}

  test_js:
    needs: [build_js]
    uses: ./.github/workflows/test_lib.yml
    with:
      lang: js
      lang-version: 18
    secrets:
      api_host: ${{ secrets.API_HOST }}
      dev_api_host: ${{ secrets.DEV_API_HOST }}
      api_key: ${{ secrets.API_KEY }}
      dev_api_key: ${{ secrets.DEV_API_KEY }}
      dev_identity_api_host: ${{ secrets.DEV_IDENTITY_API_HOST }}

  compat_go:
    needs: [test_go]
    uses: ./.github/workflows/test_compat.yml
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        lang-version: ["1.20", "1.21"]
    with:
      os: ${{ matrix.os }}
      lang: go
      lang-version: ${{ matrix.lang-version }}

  compat_python:
    needs: [test_python]
    uses: ./.github/workflows/test_compat.yml
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        lang-version: ["3.8", "3.9", "3.10"]
    with:
      os: ${{ matrix.os }}
      lang: python
      lang-version: ${{ matrix.lang-version }}

  compat_java:
    needs: [test_java]
    uses: ./.github/workflows/test_compat.yml
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        lang-version: [8, 11, 17, 19]
    with:
      os: ${{ matrix.os }}
      lang: java
      lang-version: ${{ matrix.lang-version }}

  compat_php:
    needs: [test_php]
    uses: ./.github/workflows/test_compat.yml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        lang-version: ["7.4", "8.0", "8.1", "8.2"]
    with:
      os: ${{ matrix.os }}
      lang: php
      lang-version: ${{ matrix.lang-version }}

  compat_js:
    needs: [test_js]
    uses: ./.github/workflows/test_compat.yml
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        lang-version: ["16", "18", "20"]
    with:
      os: ${{ matrix.os }}
      lang: js
      lang-version: ${{ matrix.lang-version }}

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      [test_rust, compat_js, compat_go, compat_python, compat_java, compat_php]
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      version: ${{ steps.version.outputs.version }}
      release_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Set version env
        id: version
        env:
          github_ref: ${{ github.ref }}
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: bloock ${{ steps.version.outputs.version }}
          body: |
            bloock ${{ steps.version.outputs.version }}
          draft: false
          prerelease: true

  release_rust:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release_zip
        with:
          version: ${{ needs.create_release.outputs.version }}
          release_url: ${{ needs.create_release.outputs.release_url }}
          artifact: bloock_core_lib_dynamic
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release_go:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release_zip
        with:
          version: ${{ needs.create_release.outputs.version }}
          release_url: ${{ needs.create_release.outputs.release_url }}
          artifact: bloock_lib_go
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release_php:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release_zip
        with:
          version: ${{ needs.create_release.outputs.version }}
          release_url: ${{ needs.create_release.outputs.release_url }}
          artifact: bloock_lib_php
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release_python:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release_zip
        with:
          version: ${{ needs.create_release.outputs.version }}
          release_url: ${{ needs.create_release.outputs.release_url }}
          artifact: bloock_lib_python
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release_python_wheels:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release_zip
        with:
          version: ${{ needs.create_release.outputs.version }}
          release_url: ${{ needs.create_release.outputs.release_url }}
          artifact: bloock_lib_python_wheels
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release_js:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release_zip
        with:
          version: ${{ needs.create_release.outputs.version }}
          release_url: ${{ needs.create_release.outputs.release_url }}
          artifact: bloock_lib_js
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release_java:
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release_zip
        with:
          version: ${{ needs.create_release.outputs.version }}
          release_url: ${{ needs.create_release.outputs.release_url }}
          artifact: bloock_lib_java
          github_token: ${{ secrets.GITHUB_TOKEN }}
