name: Publish JS

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      release_url:
        required: true
        type: string

jobs:
  release_js:
    name: Upload JS
    runs-on: ubuntu-latest
    steps:
      - name: Download bloock js lib
        uses: actions/download-artifact@v1
        with:
          name: bloock_lib_js
      - name: Install dependencies
        working-directory: bloock_lib_js
        run: yarn install --frozen-lockfile
      - name: Create JS release artifact
        working-directory: bloock_lib_js
        run: npm pack
      - name: Upload Js Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./bloock_lib_js/bloock-sdk-${{ inputs.version }}.tgz
          asset_name: bloock-lib-js-${{ inputs.version }}.tgz
          asset_content_type: application/gzip
