name: Release Python

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      release_url:
        required: true
        type: string

jobs:
  release_python:
    name: Upload Python
    runs-on: ubuntu-latest
    steps:
      - name: Download python wheels from package run
        uses: actions/download-artifact@v1
        with:
          name: wheel
      - name: Zip wheels
        run: zip --junk-paths -r bloock-lib-python.zip wheel/
      - name: Upload Python Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_url }}
          asset_path: ./bloock-lib-python.zip
          asset_name: bloock-lib-python-${{ inputs.version }}.zip
          asset_content_type: application/zip
