name: Test Go

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      go-version:
        required: true
        type: string
    secrets:
      api_host:
        required: true
      api_key:
        required: true

jobs:
  test_go:
    name: Test Go.
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Download go package from package run
        uses: actions/download-artifact@v1
        with:
          name: bloock_lib_go
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      - name: Test
        run: API_HOST=${{ secrets.api_host }} API_KEY=${{ secrets.api_key }} go test -v ./...
        working-directory: bloock_lib_go
      - name: Test musl
        if: runner.os == 'Linux'
        run: docker run --env API_HOST=${{ secrets.api_host }} --env API_KEY=${{ secrets.api_key }} --rm -v `pwd`:/bloock golang:${{ inputs.go-version }}-alpine /bin/sh -c 'apk add build-base && cd /bloock && go test -v ./...'
        working-directory: bloock_lib_go
      - name: Test buster
        if: runner.os == 'Linux'
        run: docker run --env API_HOST=${{ secrets.api_host }} --env API_KEY=${{ secrets.api_key }} --rm -v `pwd`:/bloock golang:${{ inputs.go-version }}-buster /bin/sh -c 'cd /bloock && go test -v ./...'
        working-directory: bloock_lib_go
