name: Test Python

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      java-version:
        required: true
        type: string
    secrets:
      api_host:
        required: true
      api_key:
        required: true

jobs:
  test_java:
    name: Test python ${{ inputs.python-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set version env
        id: version
        run: echo "::set-output name=bloock_version::$(cat VERSION)"
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Test
        run: |
          make test
        working-directory: languages/java
        env:
          API_HOST: ${{ secrets.api_host }}
          API_KEY: ${{ secrets.api_key }}
