name: Test Python

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
    secrets:
      api_host:
        required: true
      api_key:
        required: true

jobs:
  test_python:
    name: Test python ${{ inputs.python-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set version env
        id: version
        run: echo "::set-output name=bloock_version::$(cat VERSION)"
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.python-version }}
      - name: Download python wheels from package run
        uses: actions/download-artifact@v1
        with:
          name: wheel
      - name: "test"
        run: |
          pip install bloock==${{ steps.version.outputs.bloock_version }} -f ../../wheel --no-deps --no-index
          pip install bloock==${{ steps.version.outputs.bloock_version }} -f ../../wheel
          python3 -m unittest
        working-directory: languages/python
        env:
          API_HOST: ${{ secrets.api_host }}
          API_KEY: ${{ secrets.api_key }}
