name: Test Rust

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
    secrets:
      api_host:
        required: true
      api_key:
        required: true

jobs:
  test_rust:
    name: Test Rust.
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Libs
        env:
          API_KEY: ${{ secrets.api_key }}
        run: make libs-test
      - name: Test Core
        run: make core-test
      - name: Test Bridge
        run: make bridge-test
