name: Test Workflow
on:
  push:
    branches:
      - feature/EIT-3075

jobs:
  test_build:
    uses: ./.github/workflows/build_rust.yml
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cargo_command: cross
          
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cargo_command: cross

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cargo_command: cross

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            cargo_command: cross

          - os: windows-latest
            target: x86_64-pc-windows-gnu
            cargo_command: cargo

          - os: macOS-latest
            target: x86_64-apple-darwin
            cargo_command: cargo

          - os: macOS-latest
            target: aarch64-apple-darwin
            cargo_command: cargo
    with:
      os: ${{ matrix.platform.os }}
      target: ${{ matrix.platform.target }}
      cargo_command: ${{ matrix.platform.cargo_command }}
  build_wasm:
    uses: ./.github/workflows/build_wasm.yml