name: Test Lib

on:
  workflow_call:
    inputs:
      lang:
        required: true
        type: string
      lang-version:
        required: true
        type: string
      artifact:
        required: true
        type: string
    secrets:
      api_host:
        required: true
      api_key:
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup_go
        with:
          version: ${{ inputs.lang-version }}
        if: ${{ inputs.lang == "go" }}
      - uses: ./.github/actions/setup_java
        with:
          version: ${{ inputs.lang-version }}
        if: ${{ inputs.lang == "java" }}
      - uses: ./.github/actions/setup_js
        with:
          version: ${{ inputs.lang-version }}
        if: ${{ inputs.lang == "js" }}
      - uses: ./.github/actions/setup_php
        with:
          version: ${{ inputs.lang-version }}
        if: ${{ inputs.lang == "php" }}
      - uses: ./.github/actions/setup_python
        with:
          version: ${{ inputs.lang-version }}
        if: ${{ inputs.lang == "python" }}
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ inputs.artifact }}
      - name: Test
        run: make test
        env:
          API_HOST: ${{ secrets.api_host }}
          API_KEY: ${{ secrets.api_key }}
        working-directory: ${{ inputs.artifact }}
