name: Test Java

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      java-version:
        required: true
        type: string
    secrets:
      api_host:
        required: true
      api_key:
        required: true

jobs:
  test_java:
    name: Test java ${{ inputs.java-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set version env
        id: version
        shell: bash
        run: echo "bloock_version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java-version }}
      - name: Download dylibs
        uses: actions/download-artifact@v1
        with:
          name: bloock_core_lib_dynamic
      - name: Copy libraries into resources.
        run: |
          mkdir -p languages/java/src/main/resources/linux
          [[ -e bloock_core_lib_dynamic/libbloock_bridge_x86_64-unknown-linux-musl.so ]] && cp -r bloock_core_lib_dynamic/libbloock_bridge_x86_64-unknown-linux-musl.so languages/java/src/main/resources/linux/libbloock_bridge.so
          mkdir -p languages/java/src/main/resources/macos
          [[ -e bloock_core_lib_dynamic/libbloock_bridge-fat.dylib ]] && cp -r bloock_core_lib_dynamic/libbloock_bridge-fat.dylib languages/java/src/main/resources/macos/libbloock_bridge.dylib
          mkdir -p languages/java/src/main/resources/win
          [[ -e bloock_core_lib_dynamic/bloock_bridge_windows.dll ]] && cp -r bloock_core_lib_dynamic/bloock_bridge_windows.dll languages/java/src/main/resources/win/bloock_bridge.dll
          rm languages/java/Makefile
      - name: Test
        shell: bash
        run: |
          ./gradlew test
        working-directory: languages/java
        env:
          API_HOST: ${{ secrets.api_host }}
          API_KEY: ${{ secrets.api_key }}
